version: '3.9'

services:

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    networks:
      docker-net1:
        ipv4_address: 192.168.2.245
    volumes:
      - vault-config:/vault/config
      - vault-policies:/vault/policies
      - vault-data:/vault/data
      - vault-logs:/vault/logs
    environment:
      - VAULT_ADDR=http://192.168.2.245:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul

  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    networks:
      docker-net1:
        ipv4_address: 192.168.2.246
    volumes:
      - consul-config:/consul/config #/config.json
      - consul-data:/consul/data

  consul-worker:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -join consul -config-file=/consul/config/config.json
    networks:
      docker-net1:
        ipv4_address: 192.168.2.247
    volumes:
      - consul-config:/consul/config #/config.json
    depends_on:
      - consul

volumes:
  vault-config:
    external: true
  vault-policies:
    external: true
  vault-data:
    external: true
  vault-log:
    external: true
  consul-config:
    external: true
  consul-data:
    external: true

networks:
  default:
    external:
      name: docker-net1
  docker-net1:
    external: true